#!/bin/sh
# Sweep ruby/spec directories and record what mere-ruby does and does NOT
# pass, so the gap is visible from outside. This is mere-ruby's equivalent of
# the tags/filter files the other alternative implementations keep: the point
# is an honest, checked-in record of known-not-passing specs, not a green CI.
#
# For each spec file it runs the mspec shim under BOTH mere-ruby and ruby and
# compares byte-for-byte (see run_spec.sh). A file is one of:
#   MATCH  - identical output on both
#   DIFF   - runs on both, output differs (feature fidelity gap)
#   CRASH  - mere-ruby aborts where ruby does not (missing feature / bug)
#   SKIP   - ruby itself errors/does not run (unmeasurable here)
#
# Usage:
#   ./scoreboard.sh <spec-root> [dir ...]     # e.g. .../spec/ruby language core/array
#   ./scoreboard.sh <spec-root>               # default: language + core
# Writes SPEC_STATUS.md (summary table) and mspec/tags/<group>.txt (the
# per-file DIFF/CRASH records — the "known not passing" list).
set -u
here="$(cd "$(dirname "$0")" && pwd)"
root="${1:?usage: scoreboard.sh <spec-root> [dir ...]}"
shift
dirs="$*"
[ -n "$dirs" ] || dirs="language core"
tagdir="$here/tags"
mkdir -p "$tagdir"
# write to a per-pid temp and move into place at the end, so two runs never
# interleave their writes into SPEC_STATUS.md (they would produce a garbled,
# doubled table otherwise).
status="$here/../SPEC_STATUS.md.$$"
status_final="$here/../SPEC_STATUS.md"

TIMEOUT=30
run_one() {  # $1 = spec file -> echoes MATCH/DIFF/CRASH/SKIP
  out="$(perl -e "alarm $TIMEOUT; exec @ARGV" sh "$here/run_spec.sh" "$1" 2>/dev/null | tr -d '\0')"
  verdict="$(printf '%s' "$out" | tail -1)"
  if [ "$verdict" = "MATCH" ]; then echo MATCH; return; fi
  # ruby side empty tally => unmeasurable (ruby itself didn't run the examples)
  rb="$(printf '%s' "$out" | sed -n '/--- ruby:/,$p' | grep -a 'pass=' | tail -1)"
  mr="$(printf '%s' "$out" | sed -n '/--- mere-ruby:/,/--- ruby:/p' | grep -a 'pass=' | tail -1)"
  if [ -z "$rb" ]; then echo SKIP; return; fi
  if [ -z "$mr" ]; then echo CRASH; return; fi
  echo DIFF
}

# expand each requested dir to the group name + its spec files
{
  echo "# mere-ruby — ruby/spec status"
  echo
  echo "Byte-exact conformance against ruby/spec (the de-facto Ruby suite), swept by"
  echo "\`mspec/scoreboard.sh\`. Not a pass/fail gate — a checked-in record of where"
  echo "mere-ruby matches CRuby and where it does not, like the other alternative"
  echo "implementations' tags files. Per-file DIFF/CRASH lists live in \`mspec/tags/\`."
  echo
  echo "- **MATCH** identical output under mere-ruby and ruby"
  echo "- **DIFF** runs on both, output differs (fidelity gap — often an error message or a frozen check)"
  echo "- **CRASH** mere-ruby aborts where ruby does not (missing feature)"
  echo "- **SKIP** ruby itself does not run it here (mock/subprocess/platform — unmeasurable)"
  echo
  echo "| group | MATCH | DIFF | CRASH | SKIP | total |"
  echo "|---|---|---|---|---|---|"
} > "$status"

for d in $dirs; do
  group="$(printf '%s' "$d" | tr '/' '_')"
  files="$(ls "$root/$d"/*_spec.rb 2>/dev/null)"
  [ -n "$files" ] || continue
  m=0; df=0; cr=0; sk=0; tot=0
  : > "$tagdir/$group.txt"
  for f in $files; do
    tot=$((tot+1))
    v="$(run_one "$f")"
    rel="${f#$root/}"
    case "$v" in
      MATCH) m=$((m+1)) ;;
      DIFF)  df=$((df+1)); echo "DIFF  $rel"  >> "$tagdir/$group.txt" ;;
      CRASH) cr=$((cr+1)); echo "CRASH $rel"  >> "$tagdir/$group.txt" ;;
      SKIP)  sk=$((sk+1)); echo "SKIP  $rel"  >> "$tagdir/$group.txt" ;;
    esac
  done
  echo "| $d | $m | $df | $cr | $sk | $tot |" >> "$status"
  echo "$d: $m/$tot MATCH ($df diff, $cr crash, $sk skip)"
done

echo >> "$status"
echo "_Generated by \`mspec/scoreboard.sh\`; re-run to refresh._" >> "$status"
mv "$status" "$status_final"
echo "wrote $status_final and $tagdir/*.txt"
