#!/bin/sh
# Build an rbenv-installable tarball of this interpreter, and the ruby-build
# definition that installs it.
#
#   ./packaging/rbenv/package.sh <version> [base-url] [outdir]
#
# e.g. ./packaging/rbenv/package.sh 0.1.0
#
# Why a prebuilt tarball and not a source build: ruby-build's mruby and picoruby
# definitions build from source because their build tool ships with them. This
# interpreter needs the Mere compiler, which needs OCaml and dune, and none of
# that is present on a machine that has just run `rbenv install`. jruby solves
# the same problem by shipping a built artifact, and so does this -- with the
# difference that jruby's is one platform-independent jar and this is per
# platform, because the binary is native code.
#
# The definition brings its OWN build_package_* function. ruby-build sources the
# definition file into its shell, so a definition can define the strategy it
# names -- which is what makes this installable with no patch to ruby-build.
# (jruby and mruby need one only because theirs live in the script.)
set -eu
here="$(cd "$(dirname "$0")" && pwd)"
root="$here/../.."
ver="${1:?usage: package.sh <version> [base-url] [outdir]}"
base="${2:-https://github.com/284km/mere-ruby/releases/download/v$ver}"
out="${3:-$root/dist}"
[ -x "$root/mere-ruby" ] || { echo "package.sh: build ./mere-ruby first (see README)" >&2; exit 2; }

# The platform is part of the artifact NAME, not a note in the release body: a
# tarball whose name does not say what it runs on gets installed on a machine it
# cannot run on, and the failure arrives as a bad CPU type rather than as a
# missing download.
os="$(uname -s | tr '[:upper:]' '[:lower:]')"
arch="$(uname -m)"
plat="$os-$arch"
name="mere-ruby-$ver"
tarball="$name-$plat.tar.gz"

# The tarball carries the interpreter and the two documents a user needs to know
# what they installed -- notably which divergences are deliberate.
stage="$(mktemp -d)"
trap 'rm -rf "$stage"' EXIT
mkdir -p "$stage/$name/bin"
cp "$root/mere-ruby" "$stage/$name/bin/"
for doc in README.md KNOWN_GAPS.md; do
  [ -f "$root/$doc" ] && cp "$root/$doc" "$stage/$name/"
done
mkdir -p "$out"
( cd "$stage" && tar czf "$out/$tarball" "$name" )

sha="$(shasum -a 256 "$out/$tarball" | cut -d' ' -f1)"

# ONE definition for all platforms, named without the platform. The definition
# FILENAME becomes the rbenv version name, so putting the platform in it would
# make `rbenv local mere-ruby-0.1.0-darwin-arm64` the thing a project commits --
# and a .ruby-version naming one platform is wrong on every other machine.
# A definition is sourced shell, so it can pick its own download instead.
#
# The case arms are generated from the tarballs actually present in $out, so
# building on a second platform into the same directory produces a definition
# that knows both. A platform with no build gets a REFUSAL that names itself:
# falling through to some other platform's tarball would install a binary that
# cannot run, and the error would arrive as a bad CPU type much later.
def="$out/$name"
{
  printf '# ruby-build definition for mere-ruby %s -- a Ruby subset interpreter\n' "$ver"
  printf '# written in Mere. Generated by packaging/rbenv/package.sh; do not hand-edit.\n#\n'
  printf '# Install with:\n#   rbenv install ./%s\n' "$name"
  printf '# or drop this file in $(rbenv root)/plugins/ruby-build/share/ruby-build/ and\n'
  printf '#   rbenv install %s\n#\n' "$name"
  printf '# This defines its own strategy because ruby-build sources the definition into\n'
  printf '# its own shell, so no patch to ruby-build is needed.\n'
  printf 'build_package_mere_ruby() {\n'
  printf '  build_package_copy\n'
  printf '  # bin/ruby is the name rbenv shims and every tool invokes.\n'
  printf '  ln -fs mere-ruby "${PREFIX_PATH}/bin/ruby"\n'
  printf '}\n\n'
  printf 'case "$(uname -s)-$(uname -m)" in\n'
  for tb in "$out/$name"-*.tar.gz; do
    [ -f "$tb" ] || continue
    tbn="$(basename "$tb")"
    # mere-ruby-<ver>-<os>-<arch>.tar.gz -> <os>-<arch>
    p="${tbn#"$name-"}"; p="${p%.tar.gz}"
    tos="${p%-*}"; tarch="${p##*-}"
    # uname -s is capitalised (Darwin, Linux); the artifact name is lowercase.
    uos="$(printf '%s' "$tos" | awk '{ print toupper(substr($0,1,1)) substr($0,2) }')"
    tsha="$(shasum -a 256 "$tb" | cut -d' ' -f1)"
    printf '  %s-%s) __url="%s/%s"; __sha="%s" ;;\n' "$uos" "$tarch" "$base" "$tbn" "$tsha"
  done
  printf '  *) echo "mere-ruby %s: no build for $(uname -s)-$(uname -m)" >&2; exit 1 ;;\n' "$ver"
  printf 'esac\n\n'
  printf 'install_package "%s" "${__url}#${__sha}" mere_ruby\n' "$name"
} > "$def"

printf 'tarball    %s (%s)\n' "$out/$tarball" "$(du -h "$out/$tarball" | cut -f1)"
printf 'sha256     %s\n' "$sha"
printf 'definition %s (platforms: %s)\n' "$def" "$(grep -c ') __url=' "$def")"
printf '\nUpload the tarball(s) to %s\n' "$base"
printf 'then:  rbenv install %s\n' "$def"
