# Prints the Socket constants table the prelude embeds: every Integer
# constant of Socket::Constants, as "NAME=value" separated by spaces, in the
# order the running ruby lists them.
#
# The values are the PLATFORM's (AF_INET6 is 30 on darwin and 10 on linux,
# SOL_SOCKET 65535 and 1), so each platform's table is generated by a ruby
# running there and the interpreter picks one by sys_os (Mere v0.1.642):
#
#   . ./tools/ref_ruby.sh && ruby tools/gen_socket_consts.rb            # darwin
#   docker run --rm -v $PWD/tools:/t ruby:3.4-slim ruby /t/gen_socket_consts.rb
#                                                                     # linux
# (a ruby's version does not change these numbers; the C library's headers do)
require "socket"
rows = Socket::Constants.constants.filter_map do |c|
  v = Socket.const_get(c)
  v.is_a?(Integer) ? "#{c}=#{v}" : nil
end
warn "#{rows.size} socket constants"
puts rows.join(" ")
