# Generates m_sbcs.mere: for every single-byte, ASCII-compatible encoding the
# reference ruby converts to and from UTF-8, the codepoint of each upper-half
# byte (0x80..0xFF), as ruby's own transcoder answers it.
#
#   . ./tools/ref_ruby.sh && ruby --disable-gems tools/gen_sbcs_table.rb
#
# A byte the encoding leaves undefined is -1 (String#encode answers
# Encoding::UndefinedConversionError for it). An encoding is taken only when
# its lower half is ASCII byte for byte and every byte is one character, so
# the table is all that differs between it and ISO-8859-1.

rows = []
Encoding.list.sort_by(&:name).each do |enc|
  next if enc.dummy? || !enc.ascii_compatible?
  next if [Encoding::UTF_8, Encoding::US_ASCII, Encoding::ASCII_8BIT].include?(enc)
  begin
    Encoding::Converter.new(enc, Encoding::UTF_8)
    Encoding::Converter.new(Encoding::UTF_8, enc)
  rescue Encoding::ConverterNotFoundError
    next
  end
  single = (0..255).all? { |b| b.chr.force_encoding(enc).then { |s| s.valid_encoding? && s.length == 1 } }
  next unless single
  lower_ascii = (0..127).all? do |b|
    (b.chr.force_encoding(enc).encode(Encoding::UTF_8).ord rescue nil) == b
  end
  next unless lower_ascii
  upper = (128..255).map do |b|
    b.chr.force_encoding(enc).encode(Encoding::UTF_8).ord
  rescue Encoding::UndefinedConversionError, Encoding::InvalidByteSequenceError
    -1
  end
  next if upper.each_with_index.all? { |cp, i| cp == 128 + i } && enc != Encoding::ISO_8859_1
  rows << [enc.name.upcase, upper, enc.names.map(&:upcase) - [enc.name.upcase]]
end

LOOKUP = <<'MERE'
// the table, read on first use: "NAME" -> 1 for an encoding it has,
// "NAME:b" -> codepoint for an upper-half byte, "NAME#cp" -> byte back
let sbcs_m = map_new ();
let rec sbcs_cps = fn (nm: str) -> fn (s: str) -> fn (i: int) -> fn (e: int) -> fn (b: int) ->
  if i >= e then ()
  else
    (let rec stop = fn (j: int) -> (if j >= e || str_eq (char_at s j) "," then j else stop (j + 1)) in
     let j = stop i in
     let cp = int_of_str (substring s i j) in
     let _ = map_set sbcs_m (nm ++ ":" ++ str_of_int b) cp in
     let _ = (if cp >= 0 && (if map_has sbcs_m (nm ++ "#" ++ str_of_int cp) then false else true)
              then map_set sbcs_m (nm ++ "#" ++ str_of_int cp) b else ()) in
     sbcs_cps nm s (j + 1) e (b + 1));
let rec sbcs_rows_go = fn (s: str) -> fn (i: int) ->
  if i >= str_len s then ()
  else
    (let rec find = fn (j: int) -> fn (c: str) -> (if j >= str_len s || str_eq (char_at s j) c then j else find (j + 1) c) in
     let t = find i "\t" in
     let e = find (t + 1) "\n" in
     let nm = substring s i t in
     let _ = map_set sbcs_m nm 1 in
     let _ = sbcs_cps nm s (t + 1) e 128 in
     sbcs_rows_go s (e + 1));
let sbcs_al = map_new ();
let rec sbcs_al_go = fn (s: str) -> fn (i: int) ->
  if i >= str_len s then ()
  else
    (let rec find = fn (j: int) -> fn (c: str) -> (if j >= str_len s || str_eq (char_at s j) c then j else find (j + 1) c) in
     let t = find i "\t" in
     let e = find (t + 1) "\n" in
     let _ = map_set sbcs_al (substring s i t) (substring s (t + 1) e) in
     sbcs_al_go s (e + 1));
let sbcs_ensure = fn (u: unit) ->
  if map_has sbcs_m "" then ()
  else (let _ = map_set sbcs_m "" 1 in let _ = sbcs_al_go sbcs_aliases 0 in sbcs_rows_go sbcs_rows 0);
// the table's name for an UPPER-CASE encoding name or alias
let sbcs_name = fn (nm: str) -> (let _ = sbcs_ensure () in if map_has sbcs_al nm then map_get sbcs_al nm else nm);
// does the table have this encoding (an UPPER-CASE name or alias)?
let sbcs_has = fn (nm: str) -> (let _ = sbcs_ensure () in if str_eq nm "" then false else map_has sbcs_m (sbcs_name nm));
// the codepoint of byte b, -1 when the encoding leaves it undefined
let sbcs_to_cp = fn (nm: str) -> fn (b: int) ->
  if b < 128 then b else map_get sbcs_m (sbcs_name nm ++ ":" ++ str_of_int b);
// the byte of codepoint cp, -1 when the encoding has none for it
let sbcs_from_cp = fn (nm: str) -> fn (cp: int) ->
  if cp < 128 then cp
  else (let k = sbcs_name nm ++ "#" ++ str_of_int cp in
        if map_has sbcs_m k then map_get sbcs_m k else 0 - 1);
MERE

path = File.expand_path("../m_sbcs.mere", __dir__)
File.open(path, "w") do |f|
  f.puts "// GENERATED by tools/gen_sbcs_table.rb from ruby #{RUBY_VERSION} -- do not edit."
  f.puts "// The upper half (bytes 0x80..0xFF) of each single-byte, ASCII-compatible"
  f.puts "// encoding, as ruby's transcoder maps it to Unicode: one row per encoding,"
  f.puts "// `NAME<TAB>cp,cp,...` (128 codepoints, -1 where the byte is undefined)."
  f.puts "let sbcs_rows ="
  rows.each_with_index do |(name, ups, _), i|
    f.puts "  \"#{name}\\t#{ups.join(',')}\\n\"#{i == rows.size - 1 ? ';' : ' ++'}"
  end
  f.puts "// each alias ruby knows, `ALIAS<TAB>NAME`"
  als = rows.flat_map { |name, _, as| as.map { |a| "#{a}\\t#{name}\\n" } }
  f.puts "let sbcs_aliases = \"#{als.join}\";"
  f.puts LOOKUP
end
puts "gen_sbcs_table: #{rows.size} encodings -> #{path}"
