# Generates m_owners.mere: which core class or module DEFINES each builtin
# method, as the reference ruby reports it.
#
#   . ./tools/ref_ruby.sh && ruby --disable-gems tools/gen_owner_table.rb
#
# A backtrace names a builtin's frame by the method's OWNER, not by the
# receiver's class: `[1].each { caller(0) }` runs in 'Array#each', `1.then { }`
# in 'Kernel#then', `File.open(p) { }` in 'IO.open'. mere-ruby's builtins are
# arms of one dispatcher and have no owner of their own, so the owner is looked
# up here: the first ancestor of the receiver (ancestors_of, the order dispatch
# uses) that has a row naming the method.
#
# One row per owner, `Owner<TAB>names` for instance methods (public, private
# and protected -- `loop` and `Integer` are private Kernel methods and are
# frames all the same) and `Owner.<TAB>names` for singleton ones.
#
# --disable-gems so that what is listed is the core: RubyGems reopens Kernel
# (`require`, `gem`) and would put its own methods under Kernel's name. The
# namespaces skipped below are loaded by the interpreter for itself.
SKIP = /\A(Gem|DidYouMean|ErrorHighlight|SyntaxSuggest|Bundler|RubyVM|Ractor|Monitor|MonitorMixin)\b/

mods = ObjectSpace.each_object(Module).select do |m|
  n = (m.name rescue nil)
  n && n !~ /\A#/ && n !~ SKIP
end.sort_by(&:name)

rows = []
mods.each do |m|
  im = (m.instance_methods(false) + m.private_instance_methods(false) +
        m.protected_instance_methods(false)).uniq.map(&:to_s).sort
  sm = (m.singleton_methods(false) +
        m.singleton_class.private_instance_methods(false)).uniq.map(&:to_s).sort
  rows << [m.name, im] unless im.empty?
  rows << [m.name + ".", sm] unless sm.empty?
end
# the rows are Mere string literals; nothing in a method name may need escaping
bad = rows.flat_map { |_, ms| ms }.grep(/[\\"\s]/)
abort "gen_owner_table: names that would need escaping: #{bad.inspect}" unless bad.empty?

path = File.expand_path("../m_owners.mere", __dir__)
File.open(path, "w") do |f|
  f.puts "// GENERATED by tools/gen_owner_table.rb from ruby #{RUBY_VERSION} -- do not edit."
  f.puts "// Which core class or module defines each builtin method (see the generator"
  f.puts "// for why a backtrace needs it). One row per owner: `Owner<TAB>names` for"
  f.puts "// instance methods, `Owner.<TAB>names` for singleton ones."
  f.puts "let builtin_owner_rows ="
  rows.each_with_index do |(o, ms), i|
    f.puts "  \"#{o}\\t#{ms.join(" ")}\\n\"" + (i == rows.size - 1 ? ";" : " ++")
  end
end
puts "gen_owner_table: #{rows.size} rows, #{rows.sum { |_, ms| ms.size }} names -> #{path}"
