# Generates m_json_lib.mere: the RUBY half of the json library, as the
# reference ships it, turned into Mere string literals so that `require "json"`
# needs no stdlib on the load path.
#
#   . ./tools/ref_ruby.sh && ruby tools/gen_json_lib.rb > m_json_lib.mere
#
# The files are json 2.18.0's lib/ (json.rb, json/common.rb, json/ext.rb,
# json/ext/generator/state.rb, json/generic_object.rb, json/version.rb and
# json/add/*.rb), byte for byte: comments included, so a line number in a
# backtrace names the line CRuby's copy has there. They are distributed under
# Ruby's license (json's gemspec: `s.licenses = ["Ruby"]`; its LICENSE offers
# Ruby's terms or BSD-2-Clause) and keep their own headers.
#
# What is NOT here is json's C half -- ext/json/parser/parser.c and
# ext/json/generator/generator.c. mere-ruby's replacement for those is
# m_json.mere (a parser and a generator written in Mere, with the Ruby-visible
# classes JSON::Ext::ParserConfig and JSON::Ext::Generator::State around them).
# It is written by hand and is not generated from anything.
#
# The source directory is the reference's rubylibdir unless given.
require "rbconfig"
dir = ARGV[0] || RbConfig::CONFIG["rubylibdir"]
names = %w[json json/common json/ext json/ext/generator/state json/generic_object json/version]
names += Dir.glob("#{dir}/json/add/*.rb").sort.map { |f| "json/add/" + File.basename(f, ".rb") }

def lit(line)
  line.gsub(/[\\"{}\t\r]/) { |c| { "\\" => "\\\\", '"' => '\\"', "{" => "\\{", "}" => "\\}", "\t" => "\\t", "\r" => "\\r" }[c] }
end

version = File.read("#{dir}/json/version.rb")[/VERSION = '([^']+)'/, 1]
puts "// GENERATED by tools/gen_json_lib.rb from json #{version}'s lib/ -- do not edit."
puts "// The Ruby half of the json library, verbatim (see the tool for why and"
puts "// under what license). Answered by json_lib_src, which do_require asks"
puts "// after stdlib_src."
puts ""
puts "let json_lib_src = fn (name: str) ->"
puts "  let n = (if ends_with_rb name then substring name 0 (str_len name - 3) else name) in"
names.each_with_index do |n, i|
  src = File.read("#{dir}/#{n}.rb")
  puts "  #{i == 0 ? "if" : "else if"} str_eq n \"#{n}\" then"
  lines = src.lines
  lines.each_with_index do |l, j|
    body = l.chomp
    nl = l.end_with?("\n") ? "\\n" : ""
    puts "    \"#{lit(body)}#{nl}\"#{j == lines.size - 1 ? "" : " ++"}"
  end
end
puts "  else \"\";"
